name: simple_jwt
description: A simple library helps to generate JSON Web Tokens.
version: 0.1.0
homepage: https://github.com/zonble/simple_jwt
author: zonble <zonble@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
